### ISSUE TITLE
Suggestion: A bit messy having to add Goals & Actions to GameObject as components

### ISSUE THREAD

**Issue by dror-g** [toastisme/OpenGOAP#1]
Hi,

I find it a bit messy having to add all action and goal scripts to the gameobject in the editor.
Seems GOAPPlanner uses a list for goals, and populates it using `GetComponent<GOAPGoal>`, and a Dictionary fo GOAPActions.
Perhaps these can be serialized and goal/action scripts be added to GOAPPlanner in the editor?

**Comment by toastisme** [comment]
Thanks this is a good idea. I'll try to get to it this weekend.

**Comment by toastisme** [comment]
Having poked around a bit, this might be a bit more difficult than I had anticipated. As I understand it, even if the goals and actions are serialized, because they derive from monobehaviour these still need to be added as components first, before populating the list/dictionary. So to achieve this you would still need to add them as normal. These could be hidden in the inspector, but you would then need a way to update the the list/dictionary whenever a component is added or removed. For adding you could use something like [Reset](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Reset.html) or, [componentWasAdded](https://docs.unity3d.com/ScriptReference/ObjectFactory-componentWasAdded.html). But this all feels a bit messy. 

Unless I'm thinking of this the wrong way...if you've got a nice solution in mind feel free to make a PR! Wondering if there's a better solution of just customising the inspector in some way to just arrange the goals and actions neatly.

**Comment by dror-g** [comment]
Ah, I see your point. Tricky.
Honestly I don't think it's worth the effort in this case.

I came across the same problem trying to duplicate Actions: 
Wanted to have an Action template, then ceate one for each enemy in list, then return Cost specific for that target (the idea was to avoid having just one Action that always targets the nearest enemy). Ended up iterating the list in single Action with incrementing counter.
So had the same issue, and didn't find a solution for importing monobehaviour scripts from another script..

**Comment by toastisme** [comment]
Ah that's an interesting use case I hadn't considered.

This might not be exactly what you want, but I stumbled across this very nice [ComponentGrouper ](https://forum.unity.com/threads/group-components-in-inspector.513931/) code that allows you to group and hide components. I've been finding it useful so I've added it to the repo.

**Comment by dror-g** [comment]
Thanks!
As far as I'm concerned this issue can be closed, unless you want to keep it open for the future..
